cf/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

app_name = 'cf'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^download/$', views.download, name='download'),
    url(r'^safe_box/(?P<pk>[0-9]+)/$', views.SafeBoxDetail.as_view(), name='safe_box'),
    url(r'^safe_box_list/$', views.SafeBoxList.as_view(), name='safe_box_list'),
    url(r'^key/(?P<pk>[0-9]+)/$', views.KeyDetail.as_view(), name='key'),
    url(r'^key_list/$', views.KeyList.as_view(), name='key_list'),
    url(r'^upload/$', views.model_form_upload, name='upload'),
    url(r'^new_safe_box/$', views.safe_box_form, name='new_safe_box'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cfuerte/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cf/', include('cf.urls')),
]

cf/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class SafeBox(models.Model):
    git = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Key(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.ImageField(upload_to='documents', null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    safe_box = models.ForeignKey(SafeBox, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

cf/forms.py
from django import forms
from .models import Key, SafeBox


class KeyForm(forms.ModelForm):
    class Meta:
        model = Key
        fields = ('description', 'document', 'safe_box', )


class SafeBoxForm(forms.ModelForm):
    class Meta:
        model = SafeBox
        fields = ('name', )

cf/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import generic
from rest_framework import generics

from cf.forms import KeyForm, SafeBoxForm
from cf.serializers import SafeBoxSerializer, KeySerializer
from .models import SafeBox, Key
from django.http import HttpResponse
from wsgiref.util import FileWrapper
# Create your views here.


class Index(generic.View):
    model = SafeBox
    template_name = 'cf/index.html'
    context_object_name = 'list'

    @method_decorator(login_required)
    def get(self, request):
        data = []
        s_box = SafeBox.objects.all()
        for box in s_box:
            boxes = {}
            boxes['id'] = box.id
            boxes['name'] = box.name
            keys = Key.objects.filter(safe_box=box.id)

            ke = []
            for key in keys:
                k = {}
                if key.document:
                    k[key.description] = key.document.url
                else:
                    k[key.description] = 'No tiene imagen'
                ke.append(k)
            boxes['key'] = ke
            data.append(boxes)
        sal = {}
        form = KeyForm()
        sal['data'] = data
        sal['form'] = form
        return render(request, self.template_name, sal)


def download(request):

    data = request.body
    post_text = request.POST.get('item')
    file = Key.objects.get(document=data)
    # response = HttpResponse(FileWrapper(file.document, content_type='application/zip')
    # response['Content-Disposition'] = 'attachment; filename=myfile.zip'
    return None


class SafeBoxList(generics.ListCreateAPIView):
    queryset = SafeBox.objects.all()
    serializer_class = SafeBoxSerializer


class SafeBoxDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = SafeBox.objects.all()
    serializer_class = SafeBoxSerializer


class KeyList(generics.ListCreateAPIView):
    queryset = Key.objects.all()
    serializer_class = KeySerializer


class KeyDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Key.objects.all()
    serializer_class = KeySerializer


def model_form_upload(request):
    if request.method == 'POST':
        form = KeyForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('cf:index')
    else:
        form = KeyForm()
    return render(request, 'cf/index.html', {
        'form': form
    })


def safe_box_form(request):
    if request.method == 'POST':
        form = SafeBoxForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('cf:index')
    else:
        form = SafeBoxForm()
    return render(request, 'cf/new_safe_box.html', {
        'form': form
    })

templates/cf/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
  {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
{#      <meta http-equiv="refresh" content="20" />#}
    <title>Carousel Template for Bootstrap</title>

{#      Necesario para agregar un AJAX------------------------------------------------------------------------#}
    <script src="{% static 'cf/jquery-3.1.1.js' %}"></script>
    <script>
        function getCookie(c_name)
        {
            if (document.cookie.length > 0)
            {
                c_start = document.cookie.indexOf(c_name + "=");
                if (c_start != -1)
                {
                    c_start = c_start + c_name.length + 1;
                    c_end = document.cookie.indexOf(";", c_start);
                    if (c_end == -1) c_end = document.cookie.length;
                    return unescape(document.cookie.substring(c_start,c_end));
                }
            }
            return "";
         }

        $(function () {
        $.ajaxSetup({
            headers: { "X-CSRFToken": getCookie("csrftoken") }
            });
        });
    </script>
{#      --------------------------------------------------------------------------------------------#}


      <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
      <script type='text/javascript' src="http://imsky.github.io/holder/holder.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'cf:index' %}">Cinema</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                  {% if user.is_authenticated %}
                <li><a href="{% url 'cf:logout' %}?next={% url 'cf:index' %}">Log out</a></li>
                  {% else  %}
                <li><a href="{% url 'cf:login' %}">Sign in</a></li>
                  {% endif %}
              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>
<div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
            <h3>Safe Boxes:</h3>

            {% for values in data %}
                <ul>
                <li class="list-group-item"><a href="{% url 'cf:index'  %}">{{ values.name }}</a></li>
                </ul>
                {% for key in values.key %}
                    {% for k, v in key.items %}
                        <ul>
                        <li class="list-group-item"><a href="{% url 'cf:index'  %}">{{ k }}</a></li>
                        </ul>
                        <img src="{{ v }}" class="img-rounded" width="304" height="236">
                        <ul>
                        <li id="link" class="list-group-item"><a href="{% url 'cf:index'  %}">{{ v }}</a></li>
                        </ul>
                    {% endfor %}
                {% endfor %}
            {% endfor %}


        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            {% block content %}
              <form method="post" action="{% url 'cf:upload' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <button type="submit">Upload</button>
              </form>

              <p><a href="{% url 'cf:index' %}">Return to home</a></p>
            {% endblock %}
{#            <h3>Friends:</h3>#}
{#            <ul>#}
{#            {% for key, values in fri.items %}#}
{#                <li class="list-group-item"><a href="{% url 'cf:index'  %}">{{ values }}</a><span id="{{ key }}" class="text-muted"></span></li>#}
{#            {% endfor %}#}
{#            </ul>#}
        </div><!-- /.col-lg-4 -->
        <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
        <div class="col-lg-4">
{#            <h3>Name: {{ name }}</h3>#}

        </div><!-- /.col-lg-4 -->
      <button type="button" class="btn btn-default">Is Online</button>
      </div><!-- /.row -->



<!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{#    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>#}
    <script>
        $("#link").click(function(){
        $.ajax({
            type: "POST",
            url:'{% url "cf:download" %}',
            dataType: "json",
            data: { item: $("#link").text() },
            success: function(data) {
                alert(data.message);
            }
        })
        });
{#    $(window).on('beforeunload', function() {#}
{#           $.ajax(#}
{#                   {type:"POST", url:'{% url "cf:register_out" %}'})#}
{#    });#}
{##}
{#    $(document).ready(function(){#}
{#        $("button").click(function(){#}
{#            $.ajax(#}
{#                   {type:"GET", url:'{% url "cf:is_online" %}',#}
{#                       success: function(data) {#}
{#            jQuery.each(data, function(key, val) {#}
{#              $("#" + key).text(val);#}
{#            });#}
{#        }})#}
{#        });#}
{#    });#}
    </script>
  </body>
</html>

templates/cf/new_safe_box.html
{% block content %}
    <form method="post" action="{% url 'cf:new_safe_box' %}">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Upload</button>
    </form>

    <p><a href="{% url 'cf:index' %}">Return to home</a></p>
{% endblock %}